/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author IRFAN
 */
public class Petugas extends javax.swing.JFrame {

    /**
     * Creates new form Petugas
     */
    public Petugas() {
        initComponents();
    }

    public void setId(int id){
        tfidPetugas.setText("ID-"+id);
    }
    
    public String getNama(){
        return tfnamaPetugas.getText();
    }
    
    public String getUmur(){
        return tfumur.getText();
    }
    
    public String getAlamat(){
        return tfalamat.getText();
    }
    
    public String getGudang(){
        int i = cbgudang.getSelectedIndex();
        return cbgudang.getItemAt(i);
    }
    
    public int getSelectedPetugas(){
        return listPetugas.getSelectedIndex();
    }
    
    public void setDaftarPetugas(String[] daftarID){
        listPetugas.setListData(daftarID);
    }
    
    public void resetView(){
        tfnamaPetugas.setText("");
        tfumur.setText("");
        tfalamat.setText("");
        cbgudang.setSelectedIndex(0);
        listPetugas.clearSelection();
    }
    
    public JButton getBtnOk(){
        return jbok;
    }
    
    public JList<String> getDaftarPetugas(){
        return listPetugas;
    }
    
    public void addActionListener(ActionListener ae){
        jbok.addActionListener(ae);
    }
    
    public void addMouseAdapter(MouseAdapter ma){
        listPetugas.addMouseListener(ma);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nmPetugas = new javax.swing.JLabel();
        idPetugas = new javax.swing.JLabel();
        umur = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tfnamaPetugas = new javax.swing.JTextField();
        tfidPetugas = new javax.swing.JTextField();
        tfumur = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        cbgudang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPetugas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nmPetugas.setText("Nama Petugas");

        idPetugas.setText("ID petugas");

        umur.setText("Umur");

        alamat.setText("Alamat");

        tfnamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaPetugasActionPerformed(evt);
            }
        });

        tfidPetugas.setEditable(false);
        tfidPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidPetugasActionPerformed(evt);
            }
        });

        tfumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfumurActionPerformed(evt);
            }
        });

        cbgudang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Gudang");

        jbok.setText("OK");
        jbok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbokActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listPetugas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmPetugas)
                            .addComponent(idPetugas)
                            .addComponent(umur)
                            .addComponent(alamat)
                            .addComponent(jLabel1))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbgudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfnamaPetugas)
                                .addComponent(tfidPetugas)
                                .addComponent(tfumur)
                                .addComponent(tfalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbok)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmPetugas)
                    .addComponent(tfnamaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPetugas)
                    .addComponent(tfidPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umur)
                    .addComponent(tfumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbgudang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbok)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaPetugasActionPerformed

    private void tfumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfumurActionPerformed

    private void jbokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbokActionPerformed

    private void tfidPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JComboBox<String> cbgudang;
    private javax.swing.JLabel idPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbok;
    private javax.swing.JList<String> listPetugas;
    private javax.swing.JLabel nmPetugas;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfidPetugas;
    private javax.swing.JTextField tfnamaPetugas;
    private javax.swing.JTextField tfumur;
    private javax.swing.JLabel umur;
    // End of variables declaration//GEN-END:variables

    String getIDPetugas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
