/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author IRFAN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public JButton getBtnViewGudang(){
        return jbViewGudang;
    }
    
    public JButton getBtnAddPetugas(){
        return jbAddPetugas;
    }

    public JButton getBtnAddBarang(){
        return jbAddBarang;
    }
    
    public JButton getBtnClose(){
        return jbclose;
    }
    
    public void addActionListener(ActionListener ae){
        jbViewGudang.addActionListener(ae);
        jbAddPetugas.addActionListener(ae);
        jbAddBarang.addActionListener(ae);
        jbclose.addActionListener(ae);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbViewGudang = new javax.swing.JButton();
        jbAddPetugas = new javax.swing.JButton();
        jbAddBarang = new javax.swing.JButton();
        jbclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbViewGudang.setText("View Gudang");

        jbAddPetugas.setText("Add Petugas");
        jbAddPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddPetugasActionPerformed(evt);
            }
        });

        jbAddBarang.setText("Add Barang");

        jbclose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbViewGudang)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbAddBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAddPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbclose)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbViewGudang)
                .addGap(35, 35, 35)
                .addComponent(jbAddPetugas)
                .addGap(38, 38, 38)
                .addComponent(jbAddBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jbclose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddBarang;
    private javax.swing.JButton jbAddPetugas;
    private javax.swing.JButton jbViewGudang;
    private javax.swing.JButton jbclose;
    // End of variables declaration//GEN-END:variables
}
